version: '3'

services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pa55w0rd2020"
      MSSQL_PID: Express
    ports:
        - "1433:1433"

  seminarski-api:
      build: ../
      depends_on:
        - ms-sql-server
      volumes:
        - './SeedImages:/app/SeedImages'
      environment:
        - ConnectionStrings:DockerDB=Server=ms-sql-server,1433;Database=KljucZaKljuc;User=sa;Password=Pa55w0rd2020;MultipleActiveResultSets=true;ConnectRetryCount=200;TrustServerCertificate=true;
      ports: 
        - "8080:80"